"""empty message

Revision ID: 005d6de61e9a
Revises: 
Create Date: 2019-04-06 22:55:59.344785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005d6de61e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_phone', sa.Integer(), nullable=True),
    sa.Column('user_status', sa.Integer(), nullable=True),
    sa.Column('user_create_tiem', sa.DateTime(), nullable=True),
    sa.Column('user_update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_create_tiem'), 'user', ['user_create_tiem'], unique=False)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_user_update_time'), 'user', ['user_update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_update_time'), table_name='user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_user_create_tiem'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
