"""empty message

Revision ID: 4e526b490f19
Revises: 005d6de61e9a
Create Date: 2019-04-06 22:57:20.457080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e526b490f19'
down_revision = '005d6de61e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_password')
    # ### end Alembic commands ###
